export default [
  {
    id: '1',
    name: 'grocery1',
    imgUri: require('../../assets/img/groceries/grocery1.png'),
    price: 5,
    star: 2,
    category: 'Cake',
  },
  {
    id: '2',
    name: 'grocery2',
    imgUri: require('../../assets/img/groceries/grocery2.png'),
    price: 4,
    star: 5,
    category: 'Cake',
  },
  {
    id: '3',
    name: 'grocery3',
    imgUri: require('../../assets/img/groceries/grocery3.png'),
    price: 5,
    star: 2,
    category: 'Diepvries',
  },
  {
    id: '4',
    name: 'grocery4',
    imgUri: require('../../assets/img/groceries/grocery4.png'),
    price: 5,
    star: 5,
    category: 'Basisbenodigheden',
  },
  {
    id: '5',
    name: 'grocery5',
    imgUri: require('../../assets/img/groceries/grocery1.png'),
    price: 5,
    star: 2,
    category: 'Handsanitizer',
  },
  {
    id: '6',
    name: 'grocery6',
    imgUri: require('../../assets/img/groceries/grocery3.png'),
    price: 5,
    star: 4,
    category: 'Gezichtsverzorging',
  },
  {
    id: '7',
    name: 'grocery7',
    imgUri: require('../../assets/img/groceries/grocery2.png'),
    price: 5,
    star: 1,
    category: 'Conserveren',
  },
  {
    id: '8',
    name: 'grocery7',
    imgUri: require('../../assets/img/groceries/grocery2.png'),
    price: 5,
    star: 1,
    category: 'Conserveren',
  },
];
